# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{buby}
  s.version = "1.3.1"
  s.platform = %q{java}

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Eric Monti, tduehr}]
  s.date = %q{2011-12-05}
  s.description = %q{Buby is a mashup of JRuby with the popular commercial web security testing tool Burp Suite from PortSwigger.  Burp is driven from and tied to JRuby with a Java extension using the BurpExtender API.  This extension aims to add Ruby scriptability to Burp Suite with an interface comparable to the Burp's pure Java extension interface.}
  s.email = %q{emonti@matasano.com, td@matasano.com}
  s.executables = [%q{buby}]
  s.extra_rdoc_files = [
    "History.txt",
    "README.rdoc",
    "bin/buby"
  ]
  s.files = [
    "History.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/buby",
    "buby.gemspec",
    "java/buby.jar",
    "java/src/BurpExtender.java",
    "java/src/burp/IBurpExtender.java",
    "java/src/burp/IBurpExtenderCallbacks.java",
    "java/src/burp/IHttpRequestResponse.java",
    "java/src/burp/IMenuItemHandler.java",
    "java/src/burp/IScanIssue.java",
    "java/src/burp/IScanQueueItem.java",
    "lib/buby.rb",
    "lib/buby/extends.rb",
    "lib/buby/extends/buby_array_wrapper.rb",
    "lib/buby/extends/http_request_response.rb",
    "lib/buby/extends/scan_issue.rb",
    "samples/drb_buby.rb",
    "samples/drb_sample_cli.rb",
    "samples/mechanize_burp.rb",
    "samples/menu_copy_req.rb",
    "samples/poc_generator.rb",
    "samples/verb_tamperer.rb",
    "samples/watch_scan.rb",
    "test/buby_test.rb"
  ]
  s.homepage = %q{http://tduehr.github.com/buby}
  s.rdoc_options = [%q{--main}, %q{README.rdoc}]
  s.require_paths = [%q{lib}, %q{java}, %q{java}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Buby is a mashup of JRuby with the popular commercial web security testing tool Burp Suite from PortSwigger}
  s.test_files = [%q{test/buby_test.rb}]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

